name: repo-visualizer
on:
  push:
    branches:
      - main

jobs:
  mijn_eerste_job:
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
        with:
        output_file: "output-diagram.svg"
        artifact_name: "my-diagram"
        should_push: false
